### ISSUE TITLE
WhatBetter

### ISSUE THREAD

**Issue by ghost** [Timboy67678/WindowsPlusPlus#1]
Hello,

Would you mind allowing this to be cloned?
https://bitbucket.org/Timboy67678/nobetter.git

**Comment by Timboy67678** [comment]
i dont understand why you didn't just email me instead of opening an issue in one of my open source projects that has nothing to do with WhatBetter.

The nobetter clone was just renaming some stuff to re-point to the nostream.co domain name.

Any way, i have un-privatised the fork, not gonna update it or give advice/help for it, especially not here...
